version: "3.3"

services:
  backend_app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  backend_flask_mongodb:
    build:
      context: .
      dockerfile: ./flask_mongodb/Dockerfile
    volumes:
      - ./flask_mongodb:/flask_mongodb
    ports:
      - "8081:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: